# Generated by Django 5.0.6 on 2024-06-04 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bank_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bank",
            table="bank",
        ),
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
