# Generated by Django 5.0.6 on 2024-06-06 19:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bank_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bank",
            old_name="name",
            new_name="bank_name",
        ),
    ]
